name: Run Examples

on:
  pull_request:
     branches: [main]
  workflow_dispatch:

jobs:
  run_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Pull SAR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          # oneccl_bind_pt for torch 2.0.0 and python 3.10
          wget https://intel-extension-for-pytorch.s3.amazonaws.com/torch_ccl/cpu/oneccl_bind_pt-2.0.0%2Bcpu-cp310-cp310-linux_x86_64.whl
          python -m pip install oneccl_bind_pt-2.0.0+cpu-cp310-cp310-linux_x86_64.whl
          python -m pip install -e . "torch==2.0.0"

      - name: Partition Datasets
        run: |
          mkdir ~/datasets
          mkdir ~/partitioned_data
          python $GITHUB_WORKSPACE/examples/partition_graph.py --dataset-root ~/datasets --dataset-name cora --partition-out-path ~/partitioned_data/cora --num-partitions 3
          # python $GITHUB_WORKSPACE/examples/partition_graph.py --dataset-root ~/datasets --dataset-name reddit --partition-out-path ~/partitioned_data/reddit --num-partitions 3
          # python $GITHUB_WORKSPACE/examples/partition_graph.py --dataset-root ~/datasets --dataset-name ogbn-mag --partition-out-path ~/partitioned_data/ogbn_mag --num-partitions 3
          python $GITHUB_WORKSPACE/examples/partition_graph.py --dataset-root ~/datasets --dataset-name ogbn-arxiv --partition-out-path ~/partitioned_data/ogbn_arxiv --num-partitions 3

      - name: Homogenoeous Basic
        run: |
          python $GITHUB_WORKSPACE/.github/utils/simulate_env.py  --script-path $GITHUB_WORKSPACE/examples/train_homogeneous_graph_basic.py \
                                                                  --timeout 5*60 \
                                                                  --script-args '--partitioning-json-file examples/partition_data/ogbn_arxiv/ogbn-arxiv.json --ip-file ${GITHUB_WORKSPACE}/examples/ip_file --backend ccl' \
                                                                  --world-size 3
